Repository chingu-voyages/v42-geckos-team-22, pull requests merged in 2023-02, with the labels that each got.

#47 Feature/faq content
  src/pages/FAQ.jsx
Labels: bug, help wanted, task

#49 Loading Spinner Api Request
  src/assets/spinner.gif
  src/components/GameComponents/GamePlayWindow.jsx
  src/components/headerComponents/DropDown.jsx
  src/features/api/api.jsx
Labels: duplicate, wontfix

#45 Development
  .env
  index.html
  public/favicon.ico
  public/vite.svg
  src/App.jsx
  src/assets/Shapes/Circle.png
  src/assets/Shapes/Oval.png
  src/assets/Shapes/Square.png
  src/assets/Shapes/Triange.png
  src/assets/Shapes/Triangle.png
  src/assets/logo.png
  src/assets/modal/fox/foxHead.svg
  src/assets/modal/fox/foxLeftArm.svg
  src/assets/modal/fox/foxLeftLeg.svg
  src/assets/modal/fox/foxRightArm.svg
  src/assets/modal/fox/foxRightLeg.svg
  src/components/Footer.jsx
  src/components/GameComponents/GameAnswerButton.jsx
  src/components/GameComponents/GameAnswers.jsx
  src/components/GameComponents/GameControls.jsx
  src/components/GameComponents/GameEndWindow.jsx
  src/components/GameComponents/GameHeading.jsx
  src/components/GameComponents/GameLandingWindow.jsx
  src/components/GameComponents/GameLoadingWindow.jsx
  src/components/GameComponents/GamePlayWindow.jsx
  src/components/GameComponents/GameSpinnerWindow.jsx
  src/components/headerComponents/DropDown.jsx
  src/components/headerComponents/Header.jsx
  src/components/headerComponents/MobileNav.jsx
  src/components/modalComponents/EmailModal.jsx
  src/components/modalComponents/NameModal.jsx
  src/components/modalComponents/PasswordModal.jsx
  src/components/modalComponents/SignInModal.jsx
  src/components/modalComponents/SuccessModal.jsx
  src/data.js
  src/features/api/api.jsx
  src/features/flashcard/Color.jsx
  src/features/flashcard/Letter.jsx
  src/features/flashcard/Number.jsx
  src/features/flashcard/Shape.jsx
  src/global.css
  src/pages/FAQ.jsx
  src/pages/Game.jsx
  src/pages/Home.jsx
  src/pages/HomePage.jsx
  src/redux/slices/gameFunctionSlice.jsx
  src/redux/slices/headerSlice.js
  src/redux/slices/testSlice.jsx
  src/redux/store.js
  tailwind.config.cjs
Labels: epic
